### ISSUE TITLE
Fails to verify OS requirements

### ISSUE THREAD

**Issue by zumiek** [microsoft/devhome#2210]
### Dev Home version

0.1001.389.0

### Windows build number

10.0.22631.3007

### Other software

OS Build Version: 10.0.22631.3007.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

I have a newly installed Win 11 HP Elitebook.
Windows 11 Enterprise
Version	23H2
Installerad	‎2024-‎01-‎30
OS-version	22631.3007
Gränssnitt	Windows Feature Experience Pack 1000.22681.1000.0

Start of config file :
```
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# set allowPrereleases to false after preview period
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      id: OS Version Requirement
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    # Powershell 7
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powershell7
      directives:
        description: Install PowerShell 7
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    # Visual Studio 2022 Enterprise
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vsPackage
      directives:
        description: Install Visual Studio 2022 Enterprise
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudio.2022.Enterprise
        source: winget
```

### Expected result

Expected programs to be installed.

### Actual result

All the steps fails, even if I comment out assertion of OS check etc.
<img width="454" alt="image" src="https://github.com/microsoft/devhome/assets/1893244/35a7a86a-626c-456e-a97f-88602a5804c5">

Developer mode is turned on:
<img width="710" alt="image" src="https://github.com/microsoft/devhome/assets/1893244/2002f458-8255-47f2-aca9-6a7244abc2a8">

### Included System Information

CPU: 13th Gen Intel(R) Core(TM) i7-1355U
Physical Memory: 15.64GB (8.42GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1001.389.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1000.393.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.40.0_x64__cw5n1h2txyewy
