### ISSUE TITLE
How to use a simple PSM1 function

### ISSUE THREAD

**Issue by work933k** [microsoft/devhome#2741]
### Provide a description of requested docs changes

Could you please provide an example on how to run a command like this:
```
- resource: Invoke-MsBuild/Invoke-MsBuild
      directives:
        description: Invoke-MsBuild on dummy.sln
        allowPrerelease: true
      settings:
        path: C:/projects/Dummy.sln
        MsBuildParameters: ""
```
