### ISSUE TITLE
DevHome fails to install from DSC WingetPackage resource

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#2968]
### Steps to reproduce the bug

1. Create a devhome.dsc.yaml file with this DSC Resource
```
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  resources:
   ### Install DevHome
   ### -------------------------------------
   - resource: Microsoft.WinGet.DSC/WinGetPackage
     directives:
       description: Install DevHome
       allowPrerelease: true
     settings:
       id: Microsoft.DevHome
```

3. Run winget configure devhome.dsc.yaml

### Expected result

Successful installation of devhome.

### Actual result

Dev home install fails.
Apply :: WinGetPackage
  The configuration unit failed while attempting to apply the desired state.
WinGetPackage Failed installing Microsoft.DevHome. InstallStatus 'DownloadError' InstallerErrorCode '0' ExtendedError '-1978334960'
