### ISSUE TITLE
Dev Home and Dev Home Canary Fail to install from Winget Install

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#3123]
### Steps to reproduce the bug

Create a Dev Box using one of the standard VS images on Windows 11. 
Download the attached devhome.txt
Rename devhome.txt to devhome.yaml
Open an admin prompt
Run Winget configure devhome.yaml

### Expected result

Success

### Actual result

Failure
![image](https://github.com/microsoft/devhome/assets/5457010/21c6f090-23fa-402b-8542-9e6ca4a960d9)

[devhome.txt](https://github.com/user-attachments/files/15572006/devhome.txt)

**Comment by denelon** [comment]
I suspect the issue here is that the id's for the packages from the Microsoft Store need to be in quotes (They start with a 9).


```YAML
    ### Install DevHome GitHub Extension
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      dependsOn:
        - DevHome
      directives:
        description: Install DevHome GitHub Extension
        allowPrerelease: true
      settings:
        id: "9NZCC27PR6N6"
```
